export const FETCH_PROFILES_REQUEST = "FETCH_PROFILES_REQUEST";
export const FETCH_PROFILES_SUCCESS = "FETCH_PROFILES_SUCCESS";
export const FETCH_PROFILES_FAIL = "FETCH_PROFILES_FAIL";

export const SEND_SWAP_REQUEST_REQUEST = "SEND_SWAP_REQUEST_REQUEST";
export const SEND_SWAP_REQUEST_SUCCESS = "SEND_SWAP_REQUEST_SUCCESS";
export const SEND_SWAP_REQUEST_FAIL = "SEND_SWAP_REQUEST_FAIL";

export const FETCH_REQUESTS_START = "FETCH_REQUESTS_START";
export const FETCH_REQUESTS_SUCCESS = "FETCH_REQUESTS_SUCCESS";
export const FETCH_REQUESTS_FAIL = "FETCH_REQUESTS_FAIL";

export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const REJECT_REQUEST_SUCCESS = "REJECT_REQUEST_SUCCESS";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
